name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Restore dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            **/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Check Realease Status
        id: release
        run: |
          MESSAGE="${{ github.event.head_commit.message }}"
          echo "::set-output name=tag::${MESSAGE}"
          IS_RELEASE=`echo "${MESSAGE}" | grep -qP "^v\d+\.\d+\.\d+\S*$" && echo true || echo false`
          echo "::set-output name=is_release::${IS_RELEASE}"
      - name: Build JSON
        id: create-json
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "config.json"
          json: '{
            "origin": "http://localhost:3000",
            "oldApi": "http://localhost:3003",
            "client_id": ${{ secrets.CLIENT_ID }},
            "redirect_uri": "http://localhost:3000/auth/twitch/callback"
          }'
          dir: "src/"
      - name: Build
        run: npm run build
